### ISSUE TITLE
Assigning connection groups to user groups

### ISSUE THREAD

**Issue by AustinLeath** [ridvanaltun/guacamole-rest-api-documentation#3]
I know it is possible to add connections to a user group via the api as far as permissions are concerned, but is it also possible to assign a connection group to a user group? I have looked in the API documentation and all I can find is the part where you can assign a connection to a user group and not a connection group.

**Comment by ridvanaltun** [comment]
Actually, i don't know, if you can do it from Guacamole, you can do can do it same thing from API itself.

**Comment by ridvanaltun** [comment]
Hey, @AustinLeath, I added, I hope it helps.

Assign Connection Groups to User Group: https://github.com/ridvanaltun/guacamole-rest-api-documentation/blob/master/docs/PERMISSIONS.md#assign-connection-groups-to-user-group

Revoke Connection Group from User Group: https://github.com/ridvanaltun/guacamole-rest-api-documentation/blob/master/docs/PERMISSIONS.md#revoke-connection-group-from-user-group

Regards.

**Comment by AustinLeath** [comment]
Thanks! It helps a ton! Here at the University of North Texas we have been using this documentation to create an "enterprise" version of guacamole that our students will be able to use to access iMac's and Windows PC's remotely. This was one of the last features we were needing to make our synchronization script work correctly. Much appreciated!
