### ISSUE TITLE
Method AddUserToConnection - Response 501

### ISSUE THREAD

**Issue by martin11411** [ridvanaltun/guacamole-rest-api-documentation#4]
Hello,

by a call to Method AddUserToConnection we get a 501 - Not Implemented response.
Version 0.9

What we do wrong?

best regards
Martin

**Comment by ridvanaltun** [comment]
> Hello,
> 
> by a call to Method AddUserToConnection we get a 501 - Not Implemented response.
> Version 0.9
> 
> What we do wrong?
> 
> best regards
> Martin

Hey,

This documentation created for Guacamole 1.1.0. Versions before 1.x means it's a pre-release version and also means hardly-under development. Every pre-release can have breaking changes. You need to check Guacamole change log to see what's change between version 9 to 1.x or my suggestion upgrade your Guacamole version to minimum 1.1.0.
